name: grounded-diffusion
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.07.19=h06a4308_0
  - cffi=1.15.1=py38h74dc2b5_0
  - cryptography=37.0.1=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1q=h7f8727e_0
  - pip=20.3.3=py38h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchvision=0.12.0=py38_cu113
  - typing_extensions=4.3.0=py38h06a4308_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.2.0
    - addict==2.4.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - albumentations==0.4.3
    - altair==4.2.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.6.2
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - attrs==22.1.0
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - beautifulsoup4==4.11.1
    - black==21.4b2
    - bleach==6.0.0
    - blinker==1.5
    - cachetools==5.2.0
    - certifi==2022.9.24
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cloudpickle==2.2.0
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - comm==0.1.2
    - commonmark==0.9.1
    - contourpy==1.0.5
    - cycler==0.11.0
    - cython==0.29.32
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - detectron2==0.6+cu111
    - diffusers==0.3.0
    - einops==0.3.0
    - entrypoints==0.4
    - executing==1.2.0
    - fairscale==0.4.12
    - fastjsonschema==2.16.2
    - filelock==3.8.0
    - flatbuffers==2.0.7
    - fonttools==4.37.4
    - fqdn==1.5.1
    - frozenlist==1.3.1
    - fsspec==2022.8.2
    - ftfy==6.1.1
    - future==0.18.2
    - fvcore==0.1.5.post20220512
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.12.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.49.1
    - huggingface-hub==0.9.1
    - humanfriendly==10.0
    - hydra-core==1.2.0
    - idna==3.4
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - imgaug==0.2.6
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - invisible-watermark==0.1.5
    - iopath==0.1.9
    - ipykernel==6.20.2
    - ipython==8.9.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - jsonpointer==2.3
    - jsonschema==4.16.0
    - jupyter==1.0.0
    - jupyter-client==8.0.1
    - jupyter-console==6.4.4
    - jupyter-core==5.1.5
    - jupyter-events==0.6.3
    - jupyter-server==2.1.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.4
    - kornia==0.6.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.1
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - mmcls==0.24.1
    - mmcv-full==1.4.2
    - mmdet==2.22.0
    - mmpycocotools==12.0.3
    - mmsegmentation==0.20.2
    - model-index==0.1.11
    - mpmath==1.2.1
    - multidict==6.0.2
    - mypy-extensions==0.4.3
    - nbclassic==0.5.1
    - nbclient==0.7.2
    - nbconvert==7.2.9
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - networkx==2.8.6
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.23.4
    - oauthlib==3.2.1
    - omegaconf==2.2.3
    - onnx==1.12.0
    - onnxruntime==1.12.1
    - opencv-python==4.1.2.30
    - openmim==0.3.3
    - ordered-set==4.1.0
    - packaging==21.3
    - pandas==1.4.4
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.10.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.2
    - portalocker==2.5.1
    - prettytable==3.5.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.36
    - protobuf==3.19.6
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pudb==2019.2
    - pure-eval==0.2.2
    - pyarrow==9.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.5
    - pydeck==0.8.0b3
    - pydeprecate==0.3.1
    - pydot==1.4.2
    - pygments==2.13.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - python-json-logger==2.0.4
    - pytorch-lightning==1.4.2
    - pytz==2022.2.1
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==25.0.0
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - regex==2022.9.13
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==12.5.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scipy==1.9.1
    - semver==2.13.0
    - send2trash==1.8.0
    - setuptools==65.4.1
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.2
    - streamlit==1.12.2
    - sympy==1.11.1
    - tabulate==0.9.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.0.1
    - terminado==0.17.1
    - terminaltables==3.1.10
    - test-tube==0.7.5
    - tifffile==2022.8.12
    - timm==0.6.11
    - tinycss2==1.2.1
    - tokenizers==0.12.1
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.0
    - torch-fidelity==0.3.0
    - torch-tb-profiler==0.4.0
    - torchmetrics==0.6.0
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.8.1
    - transformers==4.19.2
    - tzdata==2022.2
    - tzlocal==4.2
    - uri-template==1.2.0
    - urllib3==1.26.12
    - urwid==2.1.2
    - validators==0.20.0
    - watchdog==2.1.9
    - wcwidth==0.2.5
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.0
    - werkzeug==2.2.2
    - wheel==0.37.1
    - widgetsnbextension==4.0.5
    - yacs==0.1.8
    - yapf==0.32.0
    - yarl==1.8.1
    - zipp==3.10.0


